channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=7.*
  - pip
  - xorg-libxrender 
  - xorg-libxpm 
  - python=3.9.* 
  - pandas=1.1.* 
  - xlrd=1.*
  - graphviz=2.42.*
  - aria2
